version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mydatabase
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mydatabase
    volumes:
      - ./mysql:/var/lib/mysql
